language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - pypy3
env:
  - DJANGO=2.2.17
  - DJANGO=3.0.11
install:
  - pip install -e .
  - pip install -q Django==$DJANGO
script:
  - DJANGO_SETTINGS_MODULE=suit.tests.settings django-admin test suit
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.2.17
    - python: pypy
      env: DJANGO=2.2.17
